rule compute_delta:
    input:
        delta_z="results/delta/delta_z.csv",
        metadata="results/ingestion/metadata.csv",
    output:
        delta_z_no_f1="results/delta/delta_z_no_f1.csv",
        delta_z_normalized="results/delta/delta_z_normalized.csv",
        delta_z_normalized_no_f1="results/delta/delta_z_normalized_no_f1.csv",
        delta_magnitude="results/delta/delta_magnitude.csv",
        delta_summary_stats="results/delta/delta_summary_stats.csv",
        raw_all_pca="results/delta/repr_comparison/embeddings/raw_all_pca.csv",
        raw_all_umap="results/delta/repr_comparison/embeddings/raw_all_umap.csv",
        raw_nof1_pca="results/delta/repr_comparison/embeddings/raw_nof1_pca.csv",
        raw_nof1_umap="results/delta/repr_comparison/embeddings/raw_nof1_umap.csv",
        norm_all_pca="results/delta/repr_comparison/embeddings/norm_all_pca.csv",
        norm_all_umap="results/delta/repr_comparison/embeddings/norm_all_umap.csv",
        norm_nof1_pca="results/delta/repr_comparison/embeddings/norm_nof1_pca.csv",
        norm_nof1_umap="results/delta/repr_comparison/embeddings/norm_nof1_umap.csv",
        silhouette_raw_all="results/delta/repr_comparison/silhouette/silhouette_raw_all.csv",
        silhouette_raw_nof1="results/delta/repr_comparison/silhouette/silhouette_raw_nof1.csv",
        silhouette_norm_all="results/delta/repr_comparison/silhouette/silhouette_norm_all.csv",
        silhouette_norm_nof1="results/delta/repr_comparison/silhouette/silhouette_norm_nof1.csv",
        kruskal_magnitude_stage="results/delta/repr_comparison/silhouette/kruskal_magnitude_stage.csv",
        magnitude_histogram="figures/delta/magnitude_histogram.pdf",
        magnitude_by_stage="figures/delta/magnitude_by_stage.pdf",
        delta_distributions="figures/delta/delta_distributions.pdf",
        raw_all_pca_fig="figures/delta/repr_comparison/raw_all_pca.pdf",
        raw_all_umap_fig="figures/delta/repr_comparison/raw_all_umap.pdf",
        raw_nof1_pca_fig="figures/delta/repr_comparison/raw_nof1_pca.pdf",
        raw_nof1_umap_fig="figures/delta/repr_comparison/raw_nof1_umap.pdf",
        norm_all_pca_fig="figures/delta/repr_comparison/norm_all_pca.pdf",
        norm_all_umap_fig="figures/delta/repr_comparison/norm_all_umap.pdf",
        norm_nof1_pca_fig="figures/delta/repr_comparison/norm_nof1_pca.pdf",
        norm_nof1_umap_fig="figures/delta/repr_comparison/norm_nof1_umap.pdf",
        silhouette_comparison="figures/delta/repr_comparison/silhouette_comparison.pdf",
        summary_panel_all_factors="figures/delta/repr_comparison/summary_panel_all_factors.pdf",
        summary_panel_no_factor1="figures/delta/repr_comparison/summary_panel_no_factor1.pdf",
    conda:
        "../../env/analysis.yml"
    log:
        "log/compute_delta.log"
    params:
        config="config/config.yml"
    shell:
        "mkdir -p log && python src/py/05_delta.py --config {params.config} > {log} 2>&1"
